apiVersion: v1
kind: Secret
metadata:
  name: git-provider-pac-config
type: Opaque
stringData:
  provider.token: <git-provider-api-token>
  webhook.secret: <git-provider-webhook-secret>
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-auth
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: <registry-dockerconfigjson>
