apiVersion: pipelinesascode.tekton.dev/v1alpha1
kind: Repository
metadata:
  name: <repository-name>
spec:
  url: <git-repository-url>
  git_provider:
    type: <git-provider-type>
    url: <git-provider-api-url>
    secret:
      name: git-provider-pac-config
      key: provider.token
    webhook_secret:
      name: git-provider-pac-config
      key: webhook.secret
